apiVersion: v1
kind: Service
metadata:
  name: devops-app
  namespace: devops-app
spec:
  type: LoadBalancer
  selector:
    app: devops-app
  ports:
    - protocol: TCP
      port: 80        # Exposed port
      targetPort: 5000 # Container port
