name: AWS EKS Creation

on:
  workflow_dispatch:

jobs:
  eks-resources-creation:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.6.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_KEY }}
          aws-region: us-east-1

      ######################
      # 1️⃣ EKS Module
    #   ######################
      - name: Terraform Init eks
        working-directory: ./eks
        run: terraform init

      - name: Terraform Plan eks
        working-directory: ./eks 
        run: terraform plan

      - name: Terraform Apply eks
        working-directory: ./eks 
        run: terraform apply -auto-approve