name: AWS EC2 Creation

on:
  workflow_dispatch:

jobs:
  ec2-resources-creation:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.6.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_KEY }}
          aws-region: us-east-1

      ######################
      # 1️⃣ EC2 Module
    #   ######################
      - name: Terraform Init ec2
        working-directory: ./ec2
        run: terraform init

      - name: Terraform Plan ec2
        working-directory: ./ec2  
        run: terraform plan

      - name: Terraform Apply ec2
        working-directory: ./ec2  
        run: terraform apply -auto-approve
