name: Terraform Destroy

on:
  workflow_dispatch:   # This lets you manually trigger the destroy from GitHub UI

jobs:
  resources-destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_KEY }}
          aws-region: us-east-1

      - name: Terraform Init rds
        working-directory: ./rds
        run: |
          terraform init -input=false -reconfigure

      - name: Terraform destroy rds
        working-directory: ./rds
        run: terraform destroy -auto-approve

      - name: Terraform Init internal-lb
        working-directory: ./internal-lb
        run: |
          terraform init -input=false -reconfigure

      - name: Terraform destroy internal-lb
        working-directory: ./internal-lb
        run: terraform destroy -auto-approve

    
      - name: Terraform Init ec2
        working-directory: ./ec2
        run: |
          terraform init -input=false -reconfigure

      - name: Terraform destroy ec2
        working-directory: ./ec2
        run: terraform destroy -auto-approve

        
      - name: Terraform Init security groups
        working-directory: ./security_groups
        run: |
          terraform init -input=false -reconfigure

      - name: Terraform destroy security_groups
        working-directory: ./security_groups
        run: terraform destroy -auto-approve

      - name: Terraform iam Init
        working-directory: ./iam
        run: |
          terraform init -input=false -reconfigure


      - name: Terraform destroy iam
        working-directory: ./iam
        run: terraform destroy -auto-approve


      - name: Terraform Init
        working-directory: ./vpc
        run: |
          terraform init -input=false -reconfigure


      - name: Terraform destroy VPC
        working-directory: ./vpc
        run: terraform destroy -auto-approve



